server:
  port: 8092
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: the-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: itx.examples.spring.kafka.events.deserializer.DataMessageDeserializer
